wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.3
    framework: huggingface
    huggingface_version: 4.29.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687834111.4991
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      3:
      - 13
      - 23
      4: 3.8.10
      5: 0.15.3
      6: 4.29.0
      8:
      - 5
