deepspeed --num_gpus=2 train.py \
    --model_name_or_path /root/autodl-tmp/llama-chinese-7b \
    --data_path /root/autodl-tmp/opendata \
    --bf16 False \
    --output_dir /root/autodl-tmp/output_dir_test \
    --num_train_epochs 1 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 4 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 200 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --deepspeed "./configs/default_offlload_zero2.json" \
    --tf32 False  \
    --run_name "chines-llama-7b-sft" \
    --ddp_find_unused_parameters False \
    --report_to "wandb" \
    --model_max_length 2048